name: Create State Directories with index.html

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Runs when changes are pushed to the 'main' branch

jobs:
  create-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create directories and index.html files
        run: |
          mkdir -p states
          states=("alabama" "alaska" "arizona" "arkansas" "california" "colorado" "connecticut" "delaware" "florida" "georgia" \
          "hawaii" "idaho" "illinois" "indiana" "iowa" "kansas" "kentucky" "louisiana" "maine" "maryland" \
          "massachusetts" "michigan" "minnesota" "mississippi" "missouri" "montana" "nebraska" "nevada" "newhampshire" \
          "newjersey" "newmexico" "newyork" "northcarolina" "northdakota" "ohio" "oklahoma" "oregon" "pennsylvania" \
          "rhodeisland" "southcarolina" "southdakota" "tennessee" "texas" "utah" "vermont" "virginia" \
          "washington" "westvirginia" "wisconsin" "wyoming")
          
          # Loop through the states, create directories, and add index.html files
          for state in "${states[@]}"; do
            mkdir -p "states/$state"
            echo "<!DOCTYPE html>
<html>
<head>
  <title>$state</title>
</head>
<body>
  <h1>Welcome to $state</h1>
</body>
</html>" > "states/$state/index.html"
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add states
          git commit -m "Add directories and index.html files for all 50 states" || echo "No changes to commit"
          git push || echo "Push failed"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add states
          git commit -m "Add directories and index.html files for all 50 states"
          git push
