name: Create State Directories with index.html

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Runs when changes are pushed to the 'main' branch

jobs:
  create-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create directories and index.html files
        run: |
          mkdir -p states
          states=("alabama" "alaska" "arizona" "arkansas" "california" "colorado" "connecticut" "delaware" "florida" "georgia" \
          "hawaii" "idaho" "illinois" "indiana" "iowa" "kansas" "kentucky" "louisiana" "maine" "maryland" \
          "massachusetts" "michigan" "minnesota" "mississippi" "missouri" "montana" "nebraska" "nevada" "newhampshire" \
          "newjersey" "newmexico" "newyork" "northcarolina" "northdakota" "ohio" "oklahoma" "oregon" "pennsylvania" \
          "rhodeisland" "southcarolina" "southdakota" "tennessee" "texas" "utah" "vermont" "virginia" \
          "washington" "westvirginia" "wisconsin" "wyoming")
          
          # Loop through the states, create directories, and add index.html files
          for state in "${states[@]}"; do
            mkdir -p "states/$state"
            echo "<!DOCTYPE html>
<html>
<head>
  <title>$state</title>
</head>
<body>
  <h1>Welcome to $state</h1>
</body>
</html>" > "states/$state/index.html"
          done 
