name: Create State Directories with index.html

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create directories for all states
        run: |
          mkdir -p states
          echo "Creating state directories..."
          for state in alabama alaska arizona arkansas california colorado connecticut delaware florida georgia hawaii idaho illinois indiana iowa kansas kentucky louisiana maine maryland massachusetts michigan minnesota mississippi missouri montana nebraska nevada newhampshire newjersey newmexico newyork northcarolina northdakota ohio oklahoma oregon pennsylvania rhodeisland southcarolina southdakota tennessee texas utah vermont virginia washington westvirginia wisconsin wyoming
          do
            mkdir -p "states/$state"
            echo "Directory for $state created."
          done

      - name: Add index.html files
        run: |
          echo "Adding index.html files..."
          for state in alabama alaska arizona arkansas california colorado connecticut delaware florida georgia hawaii idaho illinois indiana iowa kansas kentucky louisiana maine maryland massachusetts michigan minnesota mississippi missouri montana nebraska nevada newhampshire newjersey newmexico newyork northcarolina northdakota ohio oklahoma oregon pennsylvania rhodeisland southcarolina southdakota tennessee texas utah vermont virginia washington westvirginia wisconsin wyoming
          do
            echo "<!DOCTYPE html>
<html>
<head>
  <title>$state</title>
</head>
<body>
  <h1>Welcome to $state</h1>
</body>
</html>" > "states/$state/index.html"
            echo "index.html added for $state"
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add states
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Add directories and index.html files for all 50 states"
            git push
          fi
